### ISSUE TITLE
Mocha tests throw error while loading in Test Explorer

### ISSUE THREAD

**Issue by rajanimail1** [hbenl/vscode-mocha-test-adapter#105]
Hello,

I am seeing below error while loading mocha tests in Test Explorer. Any idea how to resolve this?
Here is the settings for "mochaExplorer.files": ["packages/2d-domains/**dist/out/**/*.{test,tests}.js"],

{ Error: Couldn't create trait "bounds" because the given list of specs contains the following invalid values
* Expected one of the types [TypeRefSpec,MetaSpec] but received this value of type "object" instead: [object Object]
    at new TraitSpec (c:\repos\domains\node_modules\@intentional\schemagen\Spec.js:293:19)
    at trait (c:\repos\domains\node_modules\@intentional\schemagen\Build.js:61:77)
    at Object.optional (c:\repos\domains\node_modules\@intentional\schemagen\Build.js:85:12)
    at Object.<anonymous> (c:\repos\domains\packages\2d-domains\dist\out\diagram\schemas\DiagramRoot.type.schema.js:34:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
  errors:
   [ { Error: Expected one of the types [TypeRefSpec,MetaSpec] but received this value of type "object" instead: [object Object]
         at TraitSpec.Error_1.AggregateError.remainder2.map (c:\repos\domains\node_modules\@intentional\schemagen\Spec.js:293:68)
         at Array.map (<anonymous>)
         at new TraitSpec (c:\repos\domains\node_modules\@intentional\schemagen\Spec.js:293:57)
         at trait (c:\repos\domains\node_modules\@intentional\schemagen\Build.js:61:77)
         at Object.optional (c:\repos\domains\node_modules\@intentional\schemagen\Build.js:85:12)
         at Object.<anonymous> (c:\repos\domains\packages\2d-domains\dist\out\diagram\schemas\DiagramRoot.type.schema.js:34:17)
         at Module._compile (internal/modules/cjs/loader.js:776:30)
         at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
         at Module.load (internal/modules/cjs/loader.js:653:32)
         at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       receivedValue: '[object Object]',
       receivedType: 'object',
       expectedTypes: [Array] } ] }

**Comment by hbenl** [comment]
I'd need a sample with which I can reproduce this.
