### ISSUE TITLE
line decorations to the source line on fail does not work with native esm in Node.js 14

### ISSUE THREAD

**Issue by lieser** [hbenl/vscode-mocha-test-adapter#107]
My tests are written as esm modules. If I execute them on Node.js using the native esm support the line decorations on fail are not shown.

The failed test's log:
```
AssertionError: expected false to be true
    at Context.<anonymous> (file:///f:/Temp/dkim_verifier@pl/test/unittest/utilsSpec.mjs.js:28:11)
    at processImmediate (internal/timers.js:456:21)

+ expected - actual

-false
+true

```
From the diagnostic logs (note that `decorations` is an empty array):
```
[2020-05-01 14:50:07.707] [INFO] Received {"type":"test","test":"f:\\Temp\\dkim_verifier@pl\\test\\unittest\\utilsSpec.mjs.js: utils [unittest] addrIsInDomain addr is in domain","state":"failed","message":"AssertionError: expected false to be true\n    at Context.<anonymous> (file:///f:/Temp/dkim_verifier@pl/test/unittest/utilsSpec.mjs.js:28:11)\n    at processImmediate (internal/timers.js:456:21)\n\n+ expected - actual\n\n-false\n+true\n","decorations":[],"description":"3ms"}
```

If I use the esm package instead of the native esm support, everything works. Note that the stack trace in AssertionError looks slightly different:

The failed test's log:
```
AssertionError: expected false to be true
    at Context.<anonymous> (test\unittest\utilsSpec.mjs.js:28:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)

+ expected - actual

-false
+true
```
From the diagnostic logs (`decorations` is not empty):
```
[2020-05-01 14:53:09.976] [INFO] Received {"type":"test","test":"f:\\Temp\\dkim_verifier@pl\\test\\unittest\\utilsSpec.mjs.js: utils [unittest] addrIsInDomain addr is in domain","state":"failed","message":"AssertionError: expected false to be true\n    at Context.<anonymous> (test\\unittest\\utilsSpec.mjs.js:28:11)\n    at processImmediate (internal/timers.js:456:21)\n    at process.topLevelDomainCallback (domain.js:137:15)\n\n+ expected - actual\n\n-false\n+true\n","decorations":[{"line":27,"message":"expected false to be true"}],"description":"3ms"}
```

**Comment by hbenl** [comment]
Thanks for the detailed bug report, I fixed this in version 2.4.0.
