### ISSUE TITLE
Express-wrapped FeathersJs app configuration issue

### ISSUE THREAD

**Issue by bridgelancer** [hbenl/vscode-mocha-test-adapter#116]
In my local development settings, the mocha test suite is managed by yarn scripts to wrap a command
`export $(cat .env.test | xargs) && mocha --recursive test/"`

Directory structure of my project: 
```
backend
  .env.test
  package.json # containing the scripts for running the test suite locally
  mocha.opts
  src
    app.js # the express-wrapped feathers app defined
    ...
  config
    test.json
  test
  ...
```

My current working project would directly use the [express-wrapped feathers app](https://docs.feathersjs.com/api/express.html#express-app) in the mocha test suite. Unfortunately, the project uses the [FeathersJs](https://docs.feathersjs.com/) and some configuration variables are loaded via the [feathers-supported configuration](https://docs.feathersjs.com/api/configuration.html#usage). This means that a large part of the configuration variables are also stored within the `config/test.json` file.

Whereas the setup works for my local workstation, it seems like the mocha explorer could not successfully retrieve the settings defined within `config/test.json`. This is an error I get back from the output console:
```
TypeError: root path required
    at Function.serveStatic [as static] (/home/michael/meeopp/meeopp-backend/backend/node_modules/serve-static/index.js:40:11)
    at Object.<anonymous> (/home/michael/meeopp/meeopp-backend/backend/src/app.js:48:22)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/michael/meeopp/meeopp-backend/backend/test/setup.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireOrImport (/home/michael/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.6.0/node_modules/mocha/lib/esm-utils.js:15:12)
    at Object.exports.loadFilesAsync (/home/michael/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.6.0/node_modules/mocha/lib/esm-utils.js:28:26)
    at Mocha.loadFilesAsync (/home/michael/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.6.0/node_modules/mocha/lib/mocha.js:386:19)
    at /home/michael/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.6.0/out/worker/bundle.js:5662:29
    at Generator.next (<anonymous>)
    at /home/michael/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.6.0/out/worker/bundle.js:88:71
    at new Promise (<anonymous>)
```
Is there any clue to resolve the situation?

**Comment by hbenl** [comment]
Please show me the settings you have for Mocha Explorer in `.vscode/settings.json`

**Comment by bridgelancer** [comment]
Here you go:

```
{
    "mochaExplorer.optsFile": "backend/mocha.opts",
    "mochaExplorer.envPath": "backend/.env.test",
    "mochaExplorer.files": "backend/test/",
    "mochaExplorer.timeout": 5000,
    "mochaExplorer.exit": true,
    "python.pythonPath": "/usr/bin/python3",
}
```

**Comment by bridgelancer** [comment]
Somehow the setting works now. Thanks anyways.
