### ISSUE TITLE
Doesn't work with es6 modules

### ISSUE THREAD

**Issue by ricardomatias** [hbenl/vscode-mocha-test-adapter#12]
Trying to use this with [esm](https://github.com/standard-things/esm) and get the following output. I'm requiring `esm` via a mocha.opts file.

Any ideas how to solve it?

`
2018-09-22 11:21:38.080] [INFO] Worker: Caught error {"stack":"/XXXX/playa/test/note.spec.js:1\n(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import Note from '../lib/Note';\n                                                                                                                                                           ^^^^^^\n\nSyntaxError: Unexpected token import\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:606:28)\n    at Object.Module._extensions..js (module.js:653:10)\n    at Module.load (module.js:561:32)\n    at tryModuleLoad (module.js:504:12)\n    at Function.Module._load (module.js:496:3)\n    at Module.require (module.js:586:17)\n    at require (internal/module.js:11:18)\n    at XXXX/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.2.0/node_modules/mocha/lib/mocha.js:250:27","message":"Unexpected token import"}
`

**Comment by hbenl** [comment]
Could you show me the full command that you use to run your tests in the console?

**Comment by hbenl** [comment]
OK, I managed to reproduce this. Not sure yet what's going on here, I'll need some more time to investigate.

**Comment by artfulhacker** [comment]
I get the same error trying to import any modules into the unit tests.

**Comment by hbenl** [comment]
I finally figured it out: If I add `"mochaExplorer.env": { "NYC_ROOT_ID": "" }` to my settings, loading and running the tests works.
The reason is that `esm` [tries to find out](https://github.com/standard-things/esm/blob/master/src/env/is-sideloaded.js) if it was "sideloaded" (not sure what this means exactly). This detection works when `mocha -r esm` is started on the command line, but not when `mocha` is started programmatically (as this test adapter does). Fortunately, `esm` contains a hack that assumes it was "sideloaded" if the `NYC_ROOT_ID` environment variable is set...

**Comment by hbenl** [comment]
I have added the automatic workaround in version 1.5.0, so requiring `esm` should now work out of the box.
