### ISSUE TITLE
Mocha hook file

### ISSUE THREAD

**Issue by carlba** [hbenl/vscode-mocha-test-adapter#127]
I have a mocha hook file with the following contents

```
export const mochaHooks = {
  beforeAll: async () => {
    await setupMockDB();
    await createTypeOrmConn();
  },
  afterAll: async () => {
    await getConnection().close();
    await tearDownMockDB();
  }
};
```

I am registering it in using the `  "mochaExplorer.require": ["ts-node/register", "server/spec/hook.ts"],` config in settings.json. I can however not get it to execute. when I execute mocha from the commandline it works fine.

**Comment by carlba** [comment]
This is the log output
```
[2020-10-02 06:29:32.409] [INFO] Running test(s) ["/Users/cbackstrom/bsdev/viewspot-pricing/server/routes/cards.spec.ts: /api/cards endpoints"] of /Users/cbackstrom/bsdev/viewspot-pricing
[2020-10-02 06:29:32.410] [DEBUG] Spawning /Users/cbackstrom/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.7.2/out/worker/bundle.js with IPC options {}
[2020-10-02 06:29:32.482] [INFO] Worker: Using the mocha package at /Users/cbackstrom/bsdev/viewspot-pricing/node_modules/mocha
[2020-10-02 06:29:32.522] [INFO] Worker: Trying require('ts-node/register')
[2020-10-02 06:29:32.686] [INFO] Worker: Trying require('/Users/cbackstrom/bsdev/viewspot-pricing/server/spec/hook.ts')
[2020-10-02 06:29:33.254] [INFO] Worker: Loading files
[2020-10-02 06:29:33.254] [INFO] Worker: Running tests
[2020-10-02 06:29:36.472] [INFO] Received {"type":"suite","suite":"undefined: ","state":"running"}
[2020-10-02 06:29:36.473] [INFO] Received {"type":"suite","suite":"/Users/cbackstrom/bsdev/viewspot-pricing/server/routes/cards.spec.ts: /api/cards endpoints","state":"running"}
[2020-10-02 06:29:36.546] [INFO] Received {"type":"test","test":"/Users/cbackstrom/bsdev/viewspot-pricing/server/routes/cards.spec.ts: /api/cards endpoints should return all cards for a device","state":"running"}
[2020-10-02 06:29:36.559] [INFO] Received {"type":"test","test":"/Users/cbackstrom/bsdev/viewspot-pricing/server/routes/cards.spec.ts: /api/cards endpoints \"before each\" hook for \"should return all cards for a device\"","state":"failed","message":"ConnectionNotFoundError: Connection \"default\" was not found.\n    at new ConnectionNotFoundError (src/error/ConnectionNotFoundError.ts:8:9)\n    at ConnectionManager.get (src/connection/ConnectionManager.ts:40:19)\n    at Object.getConnection (src/index.ts:253:35)\n    at /Users/cbackstrom/bsdev/viewspot-pricing/server/spec/mocha-global.ts:133:9\n    at Generator.next (<anonymous>)\n    at fulfilled (node_modules/tslib/tslib.js:111:62)","decorations":[]}
[2020-10-02 06:29:36.560] [INFO] Received {"type":"suite","suite":"/Users/cbackstrom/bsdev/viewspot-pricing/server/routes/cards.spec.ts: /api/cards endpoints","state":"completed","description":"87ms"}
[2020-10-02 06:29:36.561] [INFO] Received {"type":"suite","suite":"undefined: ","state":"completed","description":"90ms"}
[2020-10-02 06:29:36.561] [INFO] Received {"type":"finished"}
[2020-10-02 06:29:36.574] [INFO] Worker finished
```

**Comment by carlba** [comment]
The TypeORM connection is setup in the hooks but the hooks are not loaded when launching the Tests when running from the extension.

**Comment by ml1nk** [comment]
I have the same problem and it seems that root hooks aren't supported in the first place. I tried to add this feature in #128. Until this feature is merged or otherwise added, the patched version can be used under [MarcelLink.vscode-mocha-test-adapter](https://marketplace.visualstudio.com/items?itemName=MarcelLink.vscode-mocha-test-adapter).

**Comment by carlba** [comment]
Thankyou so much for this. I spent so much time getting this working :)

**Comment by hbenl** [comment]
I have added this version 2.8.1.

**Comment by ml1nk** [comment]
Thank you, my deprecated vscode extension is removed to avoid confusion.

**Comment by carlba** [comment]
Fantastic!
