### ISSUE TITLE
Cannot find module ‘../out/worker/bundle.js’

### ISSUE THREAD

**Issue by Tonyhaenn** [hbenl/vscode-mocha-test-adapter#138]
The extension (version 2.9) is failing to activate according to this error. I’m not quite sure where to start in debugging

```
[2021-01-18 00:07:08.021] [exthost] [error] Activating extension hbenl.vscode-mocha-test-adapter failed due to an error:
[2021-01-18 00:07:08.035] [exthost] [error] Error: Cannot find module '../out/worker/bundle.js'
Require stack:
- /home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/core.js
- /home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/adapter.js
- /home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/main.js
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
	at Function.resolve (internal/modules/cjs/helpers.js:78:19)
	at new MochaAdapterCore (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/core.js:16:37)
	at new MochaAdapter (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/adapter.js:11:9)
	at TestAdapterRegistrar.adapterFactory (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/main.js:20:113)
	at TestAdapterRegistrar.add (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/node_modules/vscode-test-adapter-util/out/registrar.js:44:30)
	at new TestAdapterRegistrar (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/node_modules/vscode-test-adapter-util/out/registrar.js:19:22)
	at /home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/main.js:20:31
	at Generator.next (<anonymous>)
	at /home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/node_modules/tslib/tslib.js:117:75
	at new Promise (<anonymous>)
	at Object.__awaiter (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/node_modules/tslib/tslib.js:113:16)
	at activate (/home/coder/.local/share/code-server/extensions/hbenl.vscode-mocha-test-adapter-2.9.0/out/main.js:11:20)
	at Function._callActivateOptional (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:934:1004)
	at Function._callActivate (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:934:655)
	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:933:137
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by omniboyOK** [comment]
Same error since update "TypeError: mocha.parallelMode is not a function"

**Comment by hbenl** [comment]
@Tonyhaenn did this work with earlier versions of this extension?
@omniboyOK the error you're seeing is a different one, I fixed this in 2.9.1

**Comment by MNorgren** [comment]
I also encountered the same issue this morning. I looked in my VS Code extensions and it was on version 2.9.0 and said reload required. After restarting VS Code, it was on 2.9.1 and the extension loaded my tests as expected.

**Comment by Tonyhaenn** [comment]
@hbenl I just installed it; so I don’t know if this was present in a prior version or not. Confirming though that updating to 2.9.1 fixed the error for me.

Thank you.
