### ISSUE TITLE
no test in explorer view

### ISSUE THREAD

**Issue by avstudio** [hbenl/vscode-mocha-test-adapter#14]
I have mocha.opts:
```
--require babel-polyfill
--compilers js:babel-core/register
--watch
--recursive
--bail
--check-leaks
--reporter spec
```

//vscode
`"mochaExplorer.files": "./test/**/*.spec.js"`

I'm not able to see list of the specs inside explorer view. Output is empty and I don't see any error.
Test are running with no problems via:
`mocha --watch --compilers js:babel-core/register ./test/**/**/*.spec.js`

I'm vscode novice.  Any help to make this work? Thanks

**Comment by avstudio** [comment]
Somehow it can't handle es6
I managed to read spec and I got this error:

```
function (exports, require, module, __filename, __dirname) { import chai from 'chai'
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:646:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by hbenl** [comment]
FYI: The reason why it didn't work initially is that this adapter doesn't support the `--compilers` option (it's [deprecated](https://github.com/mochajs/mocha/wiki/compilers-deprecation) in favor of using `--require`). That's why you had to add the `mochaExplorer.require` option.
