### ISSUE TITLE
Error: Cannot find module 'mocha.config'

### ISSUE THREAD

**Issue by tomitrescak** [hbenl/vscode-mocha-test-adapter#149]
Hi, I have apretty basic setup with typescript.

This is mu .mocharc.json

```
{
  "extension": ["ts"],
  "spec": "src/**/*.test.ts",
  "require": "ts-node/register/transpile-only"
}
```

Tests run correctly when i run them via `mocha`

But trying to init your extension I get this error:

```
Error: Cannot find module 'mocha.config'
Require stack:
- c:\Users\tomi\Projects\Github\javatojs\node_modules\mocha\lib\esm-utils.js
- c:\Users\tomi\Projects\Github\javatojs\node_modules\mocha\lib\mocha.js
- c:\Users\tomi\Projects\Github\javatojs\node_modules\mocha\index.js
- c:\Users\tomi\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.10.2\out\worker\bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at exports.requireOrImport (c:\Users\tomi\Projects\Github\javatojs\node_modules\mocha\lib\esm-utils.js:42:12)
    at c:\Users\tomi\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.10.2\out\worker\bundle.js:5691:41
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\tomi\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.10.2\out\worker\bundle.js:92:58) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\tomi\\Projects\\Github\\javatojs\\node_modules\\mocha\\lib\\esm-utils.js',
    'c:\\Users\\tomi\\Projects\\Github\\javatojs\\node_modules\\mocha\\lib\\mocha.js',
    'c:\\Users\\tomi\\Projects\\Github\\javatojs\\node_modules\\mocha\\index.js',
    'c:\\Users\\tomi\\.vscode\\extensions\\hbenl.vscode-mocha-test-adapter-2.10.2\\out\\worker\\bundle.js'
  ]
}
```

**Comment by tomitrescak** [comment]
Nevermind ... this is a consequence of some zombie configuration from times when I used this package before
