### ISSUE TITLE
How can I see output of tests?

### ISSUE THREAD

**Issue by daramasala** [hbenl/vscode-mocha-test-adapter#15]
I would like to see all the output of the test (stderr and stdout).
This is useful for example:

When comparing arrays, chai prints the actual and expected values. I couldn't find a way to see this in Test Explorer
When a test throws an exception it is valuable to see the stacktrace of the exception
I tried checking the OUTPUT tab of Test Explorer but nothing is printed there.

**Comment by hbenl** [comment]
Have you tried clicking on a failed test in the Test Explorer? That should show you the output of the test:
![peek 2018-10-05 15-53](https://user-images.githubusercontent.com/16060807/46539541-10217a80-c8b7-11e8-9c7e-7bf3b0d0118c.gif)

**Comment by daramasala** [comment]
This does not print all the information about the actual and expected results when deep comparing arrays.
For example, when I use `chai` to test arrays I get the following output when running from command line:
```
      AssertionError: expected [ 27, 22 ] to deeply equal [ 34, 22 ]
      + expected - actual

       [
      -  27
      +  34
         22
       ]
      
      at Context.it (test/calculator/returnsTests.js:53:29)
```
But when running with test explorer, the output only shows this:
```
AssertionError: expected [ 27, 22 ] to deeply equal [ 34, 22 ]
    at Context.it (test/calculator/returnsTests.js:53:29)
```
Because I compare 2d arrays with 10's of elements, it's hard to find which elements are different without the extra info.

**Comment by daramasala** [comment]
Cool, thanks!
![image](https://user-images.githubusercontent.com/1841312/46936411-fde9ce00-d066-11e8-8bf9-25d99d7675e7.png)

**Comment by hbenl** [comment]
@alexkli I have just published version 1.4.0, which adds an Output channel called "Mocha tests" that shows the output captured from stdout/stderr. The adapter will also try to assign this output to the test from which it came (unfortunately this is not 100% reliable), when you then click on the test in the Test Explorer, the output from that test will be shown in the "Test Explorer" output channel (together with the error messages if the test failed).

**Comment by alexkli** [comment]
Ok, that helps a bit! But it's a bit random - sometimes log output appears under "Mocha Tests", sometimes under "Test Explorer" output channels. I never see log output in the test explorer or in the source code for successful or skipped tests - only on test failures on the red line (which is pretty nice). And it's a bit hard to find if you don't know where to look for.

Could the output channel be opened automatically upon test runs? (Maybe that should be a configuration)

Generally, I am missing the known mocha output you get on npm test when called on the command line, making it harder to associate log messages with tests. IMO it would be great if the "Mocha Tests" log could look identical to the normal mocha log output (even if that replicates information from the test explorer).

**Comment by hbenl** [comment]
@alexkli  I have created a new issue for this because the original request in this issue (showing more information from test failures) is solved.
