### ISSUE TITLE
Test Explorer Not Working VSCode 1.62.2

### ISSUE THREAD

**Issue by ybadragon** [hbenl/vscode-mocha-test-adapter#182]
In VSCode version 1.62.2 mocha test explorer throws the following error. when loading tests This same setup works in vscode 1.62.1.

```
Error: find port exited with code 1
    at findPort (C:\TFS\Workspaces\System\ado-ext-dai\DeployApplicationInfrastructure\node_modules\sync-rpc\lib\index.js:63:11)
    at start (C:\TFS\Workspaces\System\ado-ext-dai\DeployApplicationInfrastructure\node_modules\sync-rpc\lib\index.js:32:16)
    at sendMessage (C:\TFS\Workspaces\System\ado-ext-dai\DeployApplicationInfrastructure\node_modules\sync-rpc\lib\index.js:133:17)
    at createClient (C:\TFS\Workspaces\System\ado-ext-dai\DeployApplicationInfrastructure\node_modules\sync-rpc\lib\index.js:173:27)
    at Object.<anonymous> (C:\TFS\Workspaces\System\ado-ext-dai\DeployApplicationInfrastructure\node_modules\sync-request\lib\index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
```

I can see the error is occuring in sync-rpc node module and digging into that we see 
```js
  const findPortResult = spawnSync(
    process.execPath,
    [require.resolve('./find-port')],
    {
      windowsHide: true,
    }
  );
  if (findPortResult.error) {
    if (typeof findPortResult.error === 'string') {
      throw new Error(findPortResult.error);
    }
    throw findPortResult.error;
  }
  if (findPortResult.status !== 0) {
    throw new Error(
      findPortResult.stderr.toString() ||
        'find port exited with code ' + findPortResult.status
    );
  }
.
.
.
```

This is as far as I've gotten into debugging this issue. It just started happening today when VSCode updated. Any help would be appreciated.

**Comment by hbenl** [comment]
Thanks for digging into this, it looks like you're seeing a similar issue to the one I encountered in firefox-devtools/vscode-firefox-debug#268 : In regular node.js processes, `fork(scriptPath, ...scriptArgs)` works the same as `spawn(process.execPath, [scriptPath, ...scriptArgs])`. But in child processes started from VS Code 1.62.1 and later this changed (1.62.1 broke the firefox debug adapter but I guess they made further changes in 1.62.2 that broke the `findPort` code that you show here). In the case of the firefox debug adapter I was able to fix this by replacing the `spawn` variant with the `fork` variant, but in this case you have `spawnSync` and there seems to be no `forkSync`...
But there is a fix that doesn't require you to change any code: you need to run your tests in a regular node.js process instead of one run by VS Code's bundled version of node. To do that, install node.js (if you haven't already) and set `mochaExplorer.nodePath` in your VS Code settings to the path of the node executable.

**Comment by ybadragon** [comment]
I will try this out on Monday, thanks!

**Comment by ybadragon** [comment]
This fix worked, thank you!
