### ISSUE TITLE
Issue with loading nodepath on mac

### ISSUE THREAD

**Issue by duncanf95** [hbenl/vscode-mocha-test-adapter#188]
settings:
```
{
    "mochaExplorer.files": "$test/**/*.test.ts",
    "mochaExplorer.require": ["ts-node/register", "tsconfig-paths/register"],
    "mochaExplorer.exit": true,
    "mochaExplorer.nodePath": null,
    "mocha.files.glob": "test/**/*.ts",
    "mochaExplorer.esmLoader": false,
}
```

regardless of how I set node path, when I go to the test explorer it says mocha:error and gives out this in the terminal:

```
[RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 1
	at Object.getSystemErrorName (util.js:231:11)
	at errnoException (internal/errors.js:501:21)
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at spawn (child_process.js:570:9)
	at Object.fork (child_process.js:130:10)
	at options (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/out/optsReader.js:75:49)
	at new Promise (<anonymous>)
	at MochaOptsReader.<anonymous> (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/out/optsReader.js:67:35)
	at Generator.next (<anonymous>)
	at /Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/node_modules/tslib/tslib.js:117:75
	at new Promise (<anonymous>)
	at Object.__awaiter (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/node_modules/tslib/tslib.js:113:16)
	at MochaOptsReader.readOptsUsingMocha (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/out/optsReader.js:66:24)
	at ConfigReader.<anonymous> (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/out/configReader.js:192:50)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/dfraser/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.13.0/node_modules/tslib/tslib.js:114:62)] {
  code: 'ERR_OUT_OF_RANGE'
```

seems to be having error loading node path regardless of whether it is trying to use the bundled vscode version or the version in my path. Even if my settings for the project are wrong surely it shouldn't have this much issue trying to find node?

Currently on MacOS, node version:11.15, npm version 6.7.

**Comment by hbenl** [comment]
The log shows that the extension fails while trying to load your mocha configuration (`MochaOptsReader.readOptsUsingMocha`) and that it is indeed trying to use the bundled vscode version of node (otherwise there wouldn't be `fork` in the stacktrace). So, even though this kinda looks like an internal node issue (one part of node seems to not understand an error value that it got from another part of node), I don't think this is the root cause.
Could you create a little sample project with which I could reproduce this? What version of VS Code are you using?

**Comment by duncanf95** [comment]
Thanks for getting back, will try create an example for you to have a look at for this. Don;t own original code so can;t just upload project
