### ISSUE TITLE
Error when openning testing tab

### ISSUE THREAD

**Issue by Zammy** [hbenl/vscode-mocha-test-adapter#209]
When I open testing window I get the following error:
```
TypeError: Cannot read properties of undefined (reading 'describe')
    at exports.describe (C:\Users\evgen\Work\Square4Game\node_modules\mocha\lib\mocha.js:112:26)
    at Object.<anonymous> (C:\Users\evgen\Work\Square4Game\server\src\game\Game.spec.ts:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (c:\Users\evgen\Work\Square4Game\node_modules\ts-node\src\index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (c:\Users\evgen\Work\Square4Game\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

It seems like it is trying to "evaluate" my test as javascript not typescript.

Settings inside `package.json`:
``` 
  "devDependencies": {
    "@types/chai": "^4.3.1",
    "@types/mocha": "^9.1.1",
    "chai": "^4.3.6",
    "mocha": "^9.2.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3"
  },
"mocha": {
    "extension": [
      "ts"
    ],
    "spec": "server/src/**/*.spec.ts",
    "require": "ts-node/register"
  } 
```

Settings inside `.vscode/settings.json`:
```
{
    "mochaExplorer.files": "server/src/**/*.spec.ts",
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.watch": "server/src/**/*.spec.ts"
}
```
```
$ node -v
v16.14.2
```

Running my tests with `npx mocha` has no issues.

**Comment by hbenl** [comment]
Do you have a little sample project with which I could reproduce this?

**Comment by IceBjerg** [comment]
Hi. 

I am having the same issue, but I think I found out what the problem was. 
If I am having the the following import in the beginning of the spec.ts: 
`import { describe } from 'mocha';`
then it does not work, and gives the following error: 

TypeError: Cannot read properties of undefined (reading 'describe')
    at exports.describe (D:\Munka\Projects\mocha-test-fail\node_modules\mocha\lib\mocha.js:112:26)
    at Object.<anonymous> (D:\Munka\Projects\mocha-test-fail\test\first.spec.ts:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (d:\Munka\Projects\mocha-test-fail\node_modules\ts-node\src\index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (d:\Munka\Projects\mocha-test-fail\node_modules\ts-node\src\index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

The error occurs when running from the extension, the mocha cmd command runs without a problem. 

It would be great to have the two type of execution output the same. 

Minimal setup: 

[setup.zip](https://github.com/hbenl/vscode-mocha-test-adapter/files/8896902/setup.zip)
