### ISSUE TITLE
Couldn't load options using mocha: child process exited with code 9 and signal null

### ISSUE THREAD

**Issue by dhowe** [hbenl/vscode-mocha-test-adapter#225]
Trying to add the extension to a project, and I get the following error: 
```
[Error: Couldn't load options using mocha: child process exited with code 9 and signal null
	at ChildProcess.<anonymous> (/Users/dhowe/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/optsReader.js:89:32)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)]
```

**Comment by ChuckEQX** [comment]
I get the same thing.  Have have not seen a working sample of this adapter.  Mocha runs fine from CLI:
npm test

But when hit the "Refresh Tests" it shows "Test discovery failed" and opens this:
`The worker process finished with code 1 and signal null


Stacktrace: 
	at x.syncTopLevel (c:\Users\chuck\.vscode\extensions\ms-vscode.test-adapter-converter-0.2.0\out\extension.js:5:3)
	at gh.value (c:\Users\chuck\.vscode\extensions\ms-vscode.test-adapter-converter-0.2.0\out\extension.js:2:4519)
	at T.B (file:///c:/Users/chuck/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
	at T.fire (file:///c:/Users/chuck/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
	at gh.value (c:\Users\chuck\.vscode\extensions\hbenl.vscode-test-explorer-2.22.1\out\hub\testHub.js:53:43)
	at T.B (file:///c:/Users/chuck/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:732)
	at T.fire (file:///c:/Users/chuck/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:29:950)
	at ChildProcess.<anonymous> (c:\Users\chuck\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.14.1\out\core.js:121:51)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)`

**Comment by blimmer** [comment]
We had an engineer experiencing this problem. When we enabled debug logging, we saw that he was using an old version of Node that doesn't support the `--import` flag:

```shell
[2025-05-15 15:42:15.841] [DEBUG] Using nodePath: /Users/developer/.nvm/versions/node/v18.17.1/bin/node
[2025-05-15 15:42:15.890] [ERROR] Worker (stderr): /Users/developer/.nvm/versions/node/v18.17.1/bin/node: bad option: --import=tsx
```

The project is configured to use Node 22, which supports the `--import` flag. However, they didn't have the NVM [Deeper Shell Integration](https://github.com/nvm-sh/nvm#deeper-shell-integration) installed, so it was falling back to their global version of Node (Node 18).

This engineer moved over to [`asdf`](https://asdf-vm.com/) (a superior version management system, IMO) and it resolved the issue because Mocha could use Node 22 to read the options.
