### ISSUE TITLE
A lot of `findCallLocation` errors in mocha explorer log

### ISSUE THREAD

**Issue by xluckydegen** [hbenl/vscode-mocha-test-adapter#232]
Hi,
altought my Mocha test explorer works great, when checking my Explorer Log, I see a lot of following errors:

```
[2023-01-12 16:54:40.956] [INFO] Worker: Looking for Q:\ApplicationsNodeJs\AtomixDevelopment in Error: 
    at findCallLocation (c:\Users\xxx.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.14.1\out\worker\bundle.js:918:17)
    at c:\Users\xxx\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.14.1\out\worker\bundle.js:909:30
    at file:///Q:/xxx/node_modules/ethers/analytics/classEthAnalysisDataContracts.test.ts:5:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at formattedImport (Q:\xxx\node_modules\mocha\lib\nodejs\esm-utils.js:9:14)
    at Object.exports.requireOrImport (Q:\xxx\node_modules\mocha\lib\nodejs\esm-utils.js:42:28)
    at Object.exports.loadFilesAsync (Q:\xxx\node_modules\mocha\lib\nodejs\esm-utils.js:100:20)
```

Is there anything I can do with that? Or is it normal?

Thanks

**Comment by tekumara** [comment]
Also seeing this with these call stacks:

```
[2023-07-29 01:25:19.938] [INFO] Worker: Looking for /Users/tekumara/code3/release-please in Error:
    at findCallLocation (/Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:918:17)
    at /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:909:30
    at exports.it (/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js:127:53)
    at Suite.<anonymous> (/Users/tekumara/code3/release-please/test/factories/changelog-notes-factory.ts:42:9)
    at Object.create (/Users/tekumara/code3/release-please/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/tekumara/code3/release-please/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:907:37
    at exports.describe (/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js:112:60)
    at Suite.<anonymous> (/Users/tekumara/code3/release-please/test/factories/changelog-notes-factory.ts:39:11)
    at Object.create (/Users/tekumara/code3/release-please/node_modules/mocha/lib/interfaces/common.js:148:19)
[2023-07-29 01:25:19.938] [INFO] Worker: Looking for /Users/tekumara/code3/release-please in Error:
    at findCallLocation (/Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:918:17)
    at /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:909:30
    at exports.it (/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js:127:53)
    at Suite.<anonymous> (/Users/tekumara/code3/release-please/test/commits.ts:220:5)
    at Object.create (/Users/tekumara/code3/release-please/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/tekumara/code3/release-please/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:907:37
    at exports.describe (/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js:112:60)
    at Object.<anonymous> (/Users/tekumara/code3/release-please/test/commits.ts:21:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
[2023-07-29 01:25:19.938] [INFO] Worker: Looking for /Users/tekumara/code3/release-please in Error:
    at findCallLocation (/Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:918:17)
    at /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js:909:30
    at exports.describe (/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js:112:60)
    at Object.<anonymous> (/Users/tekumara/code3/release-please/test/commits.ts:21:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by DesignByOnyx** [comment]
In the [Troubleshooting](https://github.com/hbenl/vscode-mocha-test-adapter#troubleshooting) section near the bottom of the main README it explains that this is normal as the test explorer uses the stack to find the file/line number information about individual tests. You can safely ignore these.
