### ISSUE TITLE
Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by tekumara** [hbenl/vscode-mocha-test-adapter#247]
.vscode/settings.json:
```json
{
    "cmake.configureOnOpen": false,
    "mochaExplorer.files": "out/test/**/*.js",
    "mochaExplorer.require": "source-map-support/register",
    "mochaExplorer.watch": "out/**/*.js"
}
```

The Mocha Explorer Log output panel:
```
[2023-07-29 00:51:19.103] [INFO] Test Explorer found
[2023-07-29 00:51:19.103] [INFO] Creating adapter for /Users/tekumara/code3/release-please
[2023-07-29 00:51:19.103] [INFO] Registering adapter for /Users/tekumara/code3/release-please
[2023-07-29 00:51:19.104] [INFO] Loading test files of /Users/tekumara/code3/release-please
[2023-07-29 00:51:19.104] [INFO] Initialization finished
[2023-07-29 00:51:19.104] [DEBUG] Using working directory: /Users/tekumara/code3/release-please
[2023-07-29 00:51:19.111] [INFO] Configuration changed
[2023-07-29 00:51:19.123] [INFO] Configuration changed
[2023-07-29 00:51:19.143] [DEBUG] Using nodePath: /Users/tekumara/Library/Caches/fnm_multishells/32385_1690461755219/bin/node
[2023-07-29 00:51:19.355] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":10000,"retries":0,"requires":["source-map-support/register"],"delay":false,"fullTrace":false,"exit":false,"asyncOnly":false,"parallel":false}
[2023-07-29 00:51:19.355] [DEBUG] Looking for test files ["out/test/**/*.js"] in /Users/tekumara/code3/release-please
[2023-07-29 00:51:19.360] [DEBUG] Found test files []
[2023-07-29 00:51:19.364] [DEBUG] Using environment variables from config: {}
[2023-07-29 00:51:19.365] [DEBUG] Spawning /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js with IPC options {}
[2023-07-29 00:51:19.376] [INFO] Configuration changed
[2023-07-29 00:51:19.413] [INFO] Worker: Using the mocha package at /Users/tekumara/code3/release-please/node_modules/mocha
[2023-07-29 00:51:19.529] [INFO] Worker: Patching Mocha
[2023-07-29 00:51:19.529] [INFO] Worker: Trying requireOrImport('source-map-support/register')
[2023-07-29 00:51:19.535] [INFO] Worker: Caught error Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js
- /Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js
- /Users/tekumara/code3/release-please/node_modules/mocha/index.js
- /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at exports.requireOrImport (/Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js:60:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js',
    '/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js',
    '/Users/tekumara/code3/release-please/node_modules/mocha/index.js',
    '/Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js'
  ]
}
[2023-07-29 00:51:19.535] [INFO] Received error from worker
[2023-07-29 00:51:19.536] [ERROR] Worker (stderr): node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module 'source-map-support/register'
Require stack:
- /Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js
- /Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js
- /Users/tekumara/code3/release-please/node_modules/mocha/index.js
- /Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at exports.requireOrImport (/Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js:60:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/tekumara/code3/release-please/node_modules/mocha/lib/nodejs/esm-utils.js',
    '/Users/tekumara/code3/release-please/node_modules/mocha/lib/mocha.js',
    '/Users/tekumara/code3/release-please/node_modules/mocha/index.js',
    '/Users/tekumara/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.14.1/out/worker/bundle.js'
  ]
}

Node.js v18.16.0

[2023-07-29 00:51:19.539] [INFO] Worker finished with code 1 and signal null
```

**Comment by tekumara** [comment]
Resolved by:
```
npm install --save-dev source-map-support
```
