### ISSUE TITLE
Error when loading tests...

### ISSUE THREAD

**Issue by mikeerickson** [hbenl/vscode-mocha-test-adapter#30]
I have reviewed the various related reports, but they seem to address this issue

```
TypeError: Cannot read property 'width' of undefined
    at classLabel (/Users/mikee/Documents/code/oss/messenger/test/testUtils.js:21:51)
    at Object.<anonymous> (/Users/mikee/Documents/code/oss/messenger/test/logger.spec.js:26:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/mikee/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.0/node_modules/mocha/lib/mocha.js:250:27
```

**Comment by hbenl** [comment]
I see that you've already figured out that the problem was in your testUtils script.
There is one more issue preventing your project from working fully with the Mocha Test Explorer: Tests need to have unique names, because the name is used to identify them when communicating with Mocha. I will add this to the documentation.

**Comment by hbenl** [comment]
FYI: the original issue with your testUtils script was that you `require("window-size")`, which returns `undefined` if the process is not attached to a terminal (which is the case if mocha is started by VS Code).
