### ISSUE TITLE
mocha.opts not being read properly.

### ISSUE THREAD

**Issue by Wallysburg** [hbenl/vscode-mocha-test-adapter#32]
I currently have a mocha.opts file located at test/mocha.opts that contains a single compiler option for babel: `--compilers js:babel-core/register --recursive`.

When I attempt to load my tests using the extension, the following error is outputted to the console:

`/Users/cdavis/Code/ontask/dtm/core/services/ui-dashboard/test/assets/js/components/Avatar.test.js:1
(function (exports, require, module, __filename, __dirname) { import { mount, shallow, configure } from 'enzyme';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)`

These seems to suggest that the mocha.opts file is not being read properly as the code is not being compiled through babel correctly.

**Comment by hbenl** [comment]
This adapter doesn't support the `--compilers` option because it is [deprecated](https://github.com/mochajs/mocha/wiki/compilers-deprecation) - try `--require babel-core/register` instead.
