### ISSUE TITLE
Help debugging individual tests

### ISSUE THREAD

**Issue by tagyoureit** [hbenl/vscode-mocha-test-adapter#43]
Hi,
I'm really interested in using this extension to debug my code.  I have it partially working such that it can run individual tests or the whole suite of tests.  However, when I try to debug the tests it throws errors from module(s) in my required files.

I've attached an animated gif of the problem.
![2019-03-19_22-51-15](https://user-images.githubusercontent.com/1646840/54662101-0cb33180-4a9a-11e9-81e1-f2e949f9f974.gif)

My mocha settings in settings.json are: 
```
    "mochaExplorer.exit": true,
    "mochaExplorer.logpanel": true,
    "mochaExplorer.require": [
        "specs/helpers/chai.js"
    ],
    "mochaExplorer.files": "specs/**/*.js",
    "mochaExplorer.env": {
        "NODE_ENV": "production"
    },
    "mochaExplorer.optsFile": "",
```

My test suite requires the `chai.js` file and I believe, in that file, one of the modules is throwing the an error.  The error is coming from `node_modules/nise/lib/fake-xhr/blob.js:6:9` which is being loaded by Sinon.js.  

When I try to enable the log file I don't see anything that stands out.  (Separately, per the gif, I don't see anything in any of the panels when setting `"mochaExplorer.logpanel":true`.  I would have expected/hoped to see similar output in the below file also in the output or debug windows.)

```
// mochaOut.json
[2019-03-20 06:00:18.034] [INFO] Configuration changed
[2019-03-20 06:00:19.724] [INFO] Worker: Running tests
[2019-03-20 06:00:19.848] [INFO] Received {"type":"suite","suite":"undefined: ","state":"running"}
[2019-03-20 06:00:19.859] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions","state":"running"}
[2019-03-20 06:00:19.859] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time","state":"running"}
[2019-03-20 06:00:20.155] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call","state":"running"}
[2019-03-20 06:00:20.155] [INFO] Received {"type":"test","test":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)","state":"running"}
[2019-03-20 06:00:20.184] [INFO] Received {"type":"test","test":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)","state":"passed"}
[2019-03-20 06:00:20.185] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call","state":"completed"}
[2019-03-20 06:00:20.224] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time","state":"completed"}
[2019-03-20 06:00:20.224] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions","state":"completed"}
[2019-03-20 06:00:20.226] [INFO] Received {"type":"suite","suite":"undefined: ","state":"completed"}
[2019-03-20 06:00:20.236] [INFO] Worker finished
[2019-03-20 06:00:22.757] [INFO] Debugging test(s) ["/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)"] of /Users/user/Documents/programming/nodejs-poolController
[2019-03-20 06:00:22.757] [INFO] Running test(s) ["/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)"] of /Users/user/Documents/programming/nodejs-poolController
[2019-03-20 06:00:22.757] [INFO] Starting the debug session
[2019-03-20 06:00:23.335] [INFO] Worker: Trying require('/Users/user/Documents/programming/nodejs-poolController/specs/helpers/chai.js')
[2019-03-20 06:00:27.122] [INFO] Worker: Running tests
[2019-03-20 06:00:27.200] [INFO] Received {"type":"suite","suite":"undefined: ","state":"running"}
[2019-03-20 06:00:27.249] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions","state":"running"}
[2019-03-20 06:00:27.249] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time","state":"running"}
[2019-03-20 06:00:27.474] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call","state":"running"}
[2019-03-20 06:00:27.474] [INFO] Received {"type":"test","test":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)","state":"running"}
[2019-03-20 06:00:27.503] [INFO] Received {"type":"test","test":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call fails to set a valid date/time with invalid time (should fail)","state":"passed"}
[2019-03-20 06:00:27.504] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time with an invalid HTTP REST call","state":"completed"}
[2019-03-20 06:00:27.546] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions #sets the date/time","state":"completed"}
[2019-03-20 06:00:27.547] [INFO] Received {"type":"suite","suite":"/Users/user/Documents/programming/nodejs-poolController/specs/lib/comms/server-set-datetime-FAIL.spec.js: #fails to set various functions","state":"completed"}
[2019-03-20 06:00:27.548] [INFO] Received {"type":"suite","suite":"undefined: ","state":"completed"}
[2019-03-20 06:00:27.556] [INFO] Worker finished
```

My basic setup is that I have a `chai.js` file which sets up my global require statements and some other initial logic.  Each test there after should be able to run independently.

Thoughts?
-tag

**Comment by hbenl** [comment]
If I recognize the error in your gif correctly, it says "Blob is not defined" - it looks like you're trying to run browser code in node(?) - browsers have a Blob constructor, but node doesn't. So it looks to me that this error is actually the correct behavior, you're just not seeing it when the test runs without the debugger. And because the test expects a failure (but I guess it expects a _different_ failure), it doesn't alert you to the error being thrown.

**Comment by tagyoureit** [comment]
Hi, thanks for the reply.  I've been racking my brain trying to figure out where some browser code might be called (I'm not using any).  I decided to go back to the basics and just create the most simple test I could.

```
var assert = require('assert')

describe('#ALL IN ONE FILE TESTS', function () {
    describe('#should run', function() {
        context('with run AND debug', function() {
            it('is true...', function () {
                console.log('asserting abc = abc')
                assert.equal('abc', 'abc')
            })
        })
    })
})
```

No requires, no additional files.  (I removed the require file from my settings.json as well.).  Now an error is being thrown from util.js.  I made another screen capture.  
![2019-03-21_22-21-41](https://user-images.githubusercontent.com/1646840/54802763-f1772c00-4c29-11e9-9b24-c1e21b3c28ab.gif)

I am seeing these errors in my mochaExplorer log files.
```
[2019-03-22 05:33:16.185] [INFO] Worker: Looking for /Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js in Error
    at findCallLocation (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:55:17)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:46:26
    at Suite.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:6:13)
    at Object.create (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:44:37
    at Suite.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:5:9)
    at Object.create (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:44:37
[2019-03-22 05:33:16.186] [INFO] Worker: Looking for /Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js in Error
    at findCallLocation (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:55:17)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:46:26
    at Suite.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:5:9)
    at Object.create (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:44:37
    at Suite.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:4:5)
    at Object.create (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:44:37

[2019-03-22 05:33:16.186] [INFO] Worker: Looking for /Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js in Error
    at findCallLocation (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:55:17)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:46:26
    at Suite.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:4:5)
    at Object.create (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/common.js:112:19)
    at context.describe.context.context (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/node_modules/mocha/lib/interfaces/bdd.js:40:27)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:44:37
    at Object.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

[2019-03-22 05:33:16.186] [INFO] Worker: Looking for /Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js in Error
    at findCallLocation (/Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:55:17)
    at /Users/user/.vscode/extensions/hbenl.vscode-mocha-test-adapter-1.6.2/out/worker/patchMocha.js:46:26
    at Object.<anonymous> (/Users/user/Documents/programming/nodejs-poolController/specs/ALL_IN_ONE.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

I see this for many (all?) of my test files.  If I add the `"mochaExplorer.pruneFiles": true` to settings.json I can successfully debug the test.  Does this help?  Seems like it is having trouble "patching" my tests but without really digging into your code I'm not sure what logic should be happening there.

**Comment by hbenl** [comment]
First of all, the stacktraces you see in the log file are not errors - these are used to find the locations of the tests (I monkey-patch mocha's `describe()` and `it()` functions and use the stacktraces to find their callers).
I downloaded your repo and found out what's going on: the `nise` library tries to figure out if `Blob` is available:
```
exports.isSupported = (function () {
    try {
        return !!new Blob();
    } catch (e) {
        return false;
    }
}());
```
That's fine because it catches the error that is thrown when it runs in node. But apparently you have the debugger set to break on caught exceptions
![Screenshot_2019-03-23_20-48-32](https://user-images.githubusercontent.com/16060807/54870924-1516af80-4dad-11e9-86e5-6872d8dbadb3.png)
Try to set it to only break on uncaught exceptions.

**Comment by tagyoureit** [comment]
Wow, I would not have realized that on my own.  REALLY appreciate you taking a look at this for me. 

👍
