### ISSUE TITLE
relative module resolve

### ISSUE THREAD

**Issue by bigjujube** [hbenl/vscode-mocha-test-adapter#51]
It can't find the relative module, the project uses the workspace,
So all the test files are in the subproject under packages, and the relative modules are in the root or other directories in the root directory, but I don't know where to customize the module parsing, please help, I like this plugin very much.
vscode-mocha-test-adapter : 1.9.0
vscode: 1.33.1
macos 10.14

```
{ Error: Cannot find module '@material-ui/core/utils/reactHelpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xukunlong/Desktop/work-project/material-ui-cat/material-ui/packages/material-ui/src/Menu/Menu.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (/Users/xukunlong/Desktop/work-project/material-ui-cat/material-ui/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .js] (/Users/xukunlong/Desktop/work-project/material-ui-cat/material-ui/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
```

**Comment by hbenl** [comment]
Does it work if you run mocha on the command line? If so, please post your mocha command.

**Comment by linmodev** [comment]
It works fine at the command line, but it is normal because it uses babel/register, and there is also babel module resolve plugin in babel config. This is actually what I watched when I watched the mateial-ui build library, if you want reproduce, you can see their code directly on github.@hbenl

**Comment by linmodev** [comment]
Command mocha 'packages/**/*.test.js' 'docs/**/*.test.js' --exclude '**/node_modules/**'

**Comment by hbenl** [comment]
I tried with the unit tests in [mui-org/material-ui](https://github.com/mui-org/material-ui) and got a similar error at first. But I got it to work with this configuration:
```json
	"mochaExplorer.files": [
		"test/utils/setup.js",
		"packages/**/*.test.js",
		"docs/**/*.test.js"
	],
	"mochaExplorer.env": {
		"NODE_ENV": "test"
	}
```
The `test/utils/setup.js` is from their `test/mocha.opts` file, the rest is from the `test:unit` script in their `package.json`: `cross-env NODE_ENV=test mocha 'packages/**/*.test.js' 'docs/**/*.test.js' --exclude '**/node_modules/**'`.

**Comment by linmodev** [comment]
Thank you very much, I found out that I missed the option "NODE_ENV": "test. Also if I want to replace @babel/register with ts-node/register, the following error will occur. How should this be solved?
```
/Users/xukunlong/Desktop/work-project/material-ui-cat/material-ui/test/utils/init.js:1
(function (exports, require, module, __filename, __dirname) { import enzyme from 'enzyme/build/index';
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by hbenl** [comment]
I guess it doesn't work because `ts-node/register` will only transpile `*.ts` files by default. The error message seems to indicate that `material-ui-cat/material-ui/test/utils/init.js` wasn't transpiled and so it still contains the ES6 import statements, which `node` doesn't understand.
