### ISSUE TITLE
Error when loading tests

### ISSUE THREAD

**Issue by artsjedi** [hbenl/vscode-mocha-test-adapter#7]
I got another error when load tests.:

```
[2018-08-01 13:50:56.037] [INFO] Loading test files of c:\Users\Daniel\Desktop\SoluCX\baseimporter
[2018-08-01 13:50:56.038] [DEBUG] Looking for test files test/**/*.js in c:\Users\Daniel\Desktop\SoluCX\baseimporter
[2018-08-01 13:50:56.106] [DEBUG] Found test files []
[2018-08-01 13:50:56.107] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":[],"exit":false}
[2018-08-01 13:50:56.265] [DEBUG] Using nodePath: C:\Program Files\nodejs\node.exe
[2018-08-01 13:50:56.265] [DEBUG] Using working directory: c:\Users\Daniel\Desktop\SoluCX\baseimporter
[2018-08-01 13:50:56.265] [DEBUG] Using environment variable config: {}
[2018-08-01 13:50:56.690] [INFO] Worker: Patching Mocha
[2018-08-01 13:50:56.692] [INFO] Worker: Loading files
[2018-08-01 13:50:56.692] [INFO] Worker: Converting tests and suites
[2018-08-01 13:50:56.694] [INFO] Worker: Caught error {"stack":"TypeError [ERR_MISSING_ARGS]: The 
\"message\" argument must be specified\n    at process.target._send (internal/child_process.js:601:13)
\n    at process.target.send (internal/child_process.js:586:19)\n    at process.send 
(C:\\Users\\Daniel\\.vscode\\extensions\\hbenl.vscode-mocha-test-adapter-1.0.1
\\out\\worker\\loadTests.js:9:57)\n    at Object.<anonymous> (C:\\Users\\Daniel\\.vscode\\extensions\\hbenl.vscode-mocha-test-adapter-1.0.1
\\out\\worker\\loadTests.js:50:9)\n    at Module._compile (module.js:652:30)\n    at 
Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at 
tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at 
Function.Module.runMain (module.js:693:10)","message":"The \"message\" argument must be specified"}

[2018-08-01 13:50:56.703] [INFO] Worker finished
```

**Comment by hbenl** [comment]
Thanks for pointing this out. This should not have any negative effect apart from making the diagnostic log confusing for users. In version 1.0.2 (which I just published) this error should not appear anymore.
