### ISSUE TITLE
Version 2.2 loading tests fails with "No error for last overload signature" in typescript

### ISSUE THREAD

**Issue by ManfredLange** [hbenl/vscode-mocha-test-adapter#76]
We have a large number of mocha tests (several thousands) in a repository. When opening the workspace for that repo mocha-test-adapter tries to load the tests but fails with the following stack trace in the output:

```
Error: Debug Failure. No error for last overload signature
    at resolveCall (/app/node_modules/typescript/lib/typescript.js:55202:38)
    at resolveNewExpression (/app/node_modules/typescript/lib/typescript.js:55611:24)
    at resolveSignature (/app/node_modules/typescript/lib/typescript.js:55906:28)
    at getResolvedSignature (/app/node_modules/typescript/lib/typescript.js:55935:26)
    at checkCallExpression (/app/node_modules/typescript/lib/typescript.js:56017:29)
    at checkExpressionWorker (/app/node_modules/typescript/lib/typescript.js:58295:28)
    at checkExpression (/app/node_modules/typescript/lib/typescript.js:58205:38)
    at checkNonNullExpression (/app/node_modules/typescript/lib/typescript.js:53932:37)
    at checkPropertyAccessExpression (/app/node_modules/typescript/lib/typescript.js:53977:85)
    at checkExpressionWorker (/app/node_modules/typescript/lib/typescript.js:58284:28)
    at checkExpression (/app/node_modules/typescript/lib/typescript.js:58205:38)
    at resolveCallExpression (/app/node_modules/typescript/lib/typescript.js:55473:28)
    at resolveSignature (/app/node_modules/typescript/lib/typescript.js:55904:28)
    at getResolvedSignature (/app/node_modules/typescript/lib/typescript.js:55935:26)
    at checkCallExpression (/app/node_modules/typescript/lib/typescript.js:56017:29)
    at checkExpressionWorker (/app/node_modules/typescript/lib/typescript.js:58295:28)
    at checkExpression (/app/node_modules/typescript/lib/typescript.js:58205:38)
    at checkExpressionForMutableLocation (/app/node_modules/typescript/lib/typescript.js:57994:24)
    at checkPropertyAssignment (/app/node_modules/typescript/lib/typescript.js:58006:20)
    at checkObjectLiteral (/app/node_modules/typescript/lib/typescript.js:53159:83)
    at checkExpressionWorker (/app/node_modules/typescript/lib/typescript.js:58282:28)
    at checkExpression (/app/node_modules/typescript/lib/typescript.js:58205:38)
    at checkExpressionCached (/app/node_modules/typescript/lib/typescript.js:57914:38)
    at getTypeOfExpression (/app/node_modules/typescript/lib/typescript.js:58181:28)
    at checkDeclarationInitializer (/app/node_modules/typescript/lib/typescript.js:57925:24)
    at getTypeForVariableLikeDeclaration (/app/node_modules/typescript/lib/typescript.js:39160:28)
    at getWidenedTypeForVariableLikeDeclaration (/app/node_modules/typescript/lib/typescript.js:39456:56)
    at getTypeOfVariableOrParameterOrPropertyWorker (/app/node_modules/typescript/lib/typescript.js:39587:24)
```

We switched on logging and it shows that it can find the files with the tests. There are also a lot of of sections in the log that contain "[INFO] Worker: Looking for <some path> in Error", which I ignored as they are expected as per the README.md.

I've attached the log file in which I had to redact a few things for confidentiality reasons. Please note that is also contains a lot of non-printable characters at the beginning. I removed several hundred KB's of those and left a few in there. This suggests that perhaps something with the logging code is not quite right.

As it stands this we are observing this issue in one repository but not in others. We were not able to find any relevant differences between the repository other than the one in which listing the tests fails, has several thousand tests, whereas the one in which listing tests works has only a few dozen.
[2019-12-11.log](https://github.com/hbenl/vscode-mocha-test-adapter/files/3947051/2019-12-11.log)

Any suggestions for how to diagnose this further would be very much appreciated. Thank you!

Environment:
- VS Code, version 1.40.2
- vscode-mocha-test-adapter, version 2.2.0
- Typescript 3.7.2
- ts-node 8.5.2
- ts-loader 6.2.1
- mocha 6.2.2
- Node: 10.13.0

**Comment by hbenl** [comment]
Thanks for the detailed bugreport. This sounds like it could be a [Typescript bug](https://github.com/microsoft/TypeScript/issues/35186).
