### ISSUE TITLE
Not reflected test result in test explorer ui

### ISSUE THREAD

**Issue by dfdgsdfg** [hbenl/vscode-mocha-test-adapter#80]
https://code.visualstudio.com/docs/editor/multi-root-workspaces

Test explorer shows tests normally. Also, it can run normally.

But test result does not seem to be reflected normally.

In OUTPUT > Mocha Explorer Log shows that everything works fine which is test running, results, etc.

In Test explorer look everything is just same as before running test.

Result of test running:
<img width="260" alt="스크린샷 2019-12-18 오후 4 39 06" src="https://user-images.githubusercontent.com/474775/71065679-0aab0a00-21b5-11ea-84fa-0968fea1b4dc.png">

**Comment by hbenl** [comment]
Multi-root workspaces are supported, so the problem must be something else. Could you attach the output from the Mocha Explorer Log?

**Comment by dfdgsdfg** [comment]
Here is more information.

`.vscode/settings.json`
```josn
{
  "eslint.alwaysShowStatus": true,
  "eslint.workingDirectories": [{
    "directory": "functions",
    "changeProcessCWD": true
  }],
  "mochaExplorer.files": "${workspaceFolder:functions}/test/**/*.test.js",
  "mochaExplorer.logpanel": true
}
```

Log
```
[2019-12-19 02:05:02.927] [INFO] Test Explorer found
[2019-12-19 02:05:02.927] [INFO] Creating adapter for /Users/dididi/workspaces/effy/effy-functions
[2019-12-19 02:05:02.928] [INFO] Registering adapter for /Users/dididi/workspaces/effy/effy-functions
[2019-12-19 02:05:02.928] [INFO] Loading test files of /Users/dididi/workspaces/effy/effy-functions
[2019-12-19 02:05:02.928] [INFO] Creating adapter for /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:05:02.928] [INFO] Registering adapter for /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:05:02.929] [INFO] Loading test files of /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:05:02.929] [INFO] Initialization finished
[2019-12-19 02:05:02.929] [DEBUG] Using working directory: /Users/dididi/workspaces/effy/effy-functions
[2019-12-19 02:05:02.936] [DEBUG] Using working directory: /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:05:04.531] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":[],"exit":false}
[2019-12-19 02:05:04.542] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":[],"exit":false}
[2019-12-19 02:05:04.551] [DEBUG] Using nodePath: undefined
[2019-12-19 02:05:04.553] [DEBUG] Using environment variables from config: {}
[2019-12-19 02:05:04.553] [DEBUG] Looking for test files ["${workspaceFolder:functions}/test/**/*.test.js"] in /Users/dididi/workspaces/effy/effy-functions
[2019-12-19 02:05:04.559] [DEBUG] Using nodePath: undefined
[2019-12-19 02:05:04.560] [DEBUG] Using environment variables from config: {}
[2019-12-19 02:05:04.560] [DEBUG] Looking for test files ["test/**/*.js"] in /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:05:04.776] [DEBUG] Found test files ["/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js","/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js"]
[2019-12-19 02:05:04.776] [DEBUG] Found test files []
[2019-12-19 02:05:05.143] [INFO] Worker: Using the mocha package at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/node_modules/mocha
[2019-12-19 02:05:05.168] [INFO] Worker: Using the mocha package at /Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha
[2019-12-19 02:05:05.512] [INFO] Worker: Patching Mocha
[2019-12-19 02:05:05.516] [INFO] Worker: Loading files
[2019-12-19 02:05:05.519] [INFO] Worker: Patching describe
[2019-12-19 02:05:05.519] [INFO] Worker: Patching describe.skip
[2019-12-19 02:05:05.519] [INFO] Worker: Patching describe.only
[2019-12-19 02:05:05.519] [INFO] Worker: Patching it
[2019-12-19 02:05:05.519] [INFO] Worker: Patching it.only
[2019-12-19 02:05:05.519] [INFO] Worker: Patching it.skip
[2019-12-19 02:05:05.519] [INFO] Worker: Copying it.retries
[2019-12-19 02:05:05.519] [INFO] Worker: Patching context
[2019-12-19 02:05:05.519] [INFO] Worker: Patching context.skip
[2019-12-19 02:05:05.519] [INFO] Worker: Patching context.only
[2019-12-19 02:05:05.519] [INFO] Worker: Patching specify
[2019-12-19 02:05:05.519] [INFO] Worker: Patching specify.only
[2019-12-19 02:05:05.519] [INFO] Worker: Patching specify.skip
[2019-12-19 02:05:05.519] [INFO] Worker: Copying specify.retries
[2019-12-19 02:05:05.520] [INFO] Worker: Patching describe
[2019-12-19 02:05:05.520] [INFO] Worker: Patching describe.skip
[2019-12-19 02:05:05.520] [INFO] Worker: Patching describe.only
[2019-12-19 02:05:05.520] [INFO] Worker: Patching it
[2019-12-19 02:05:05.520] [INFO] Worker: Patching it.only
[2019-12-19 02:05:05.520] [INFO] Worker: Patching it.skip
[2019-12-19 02:05:05.520] [INFO] Worker: Copying it.retries
[2019-12-19 02:05:05.520] [INFO] Worker: Patching context
[2019-12-19 02:05:05.520] [INFO] Worker: Patching context.skip
[2019-12-19 02:05:05.520] [INFO] Worker: Patching context.only
[2019-12-19 02:05:05.520] [INFO] Worker: Patching specify
[2019-12-19 02:05:05.520] [INFO] Worker: Patching specify.only
[2019-12-19 02:05:05.520] [INFO] Worker: Patching specify.skip
[2019-12-19 02:05:05.520] [INFO] Worker: Copying specify.retries
[2019-12-19 02:05:05.556] [INFO] Worker: Patching Mocha
[2019-12-19 02:05:05.584] [INFO] Worker: Loading files
[2019-12-19 02:05:05.591] [INFO] 

[2019-12-19 02:05:05.592] [INFO] 

[2019-12-19 02:05:05.593] [INFO]   0 passing (6ms)

[2019-12-19 02:05:05.593] [INFO] 

[2019-12-19 02:05:05.593] [INFO] Worker: Converting tests and suites
[2019-12-19 02:05:05.594] [INFO] Worker found no tests
[2019-12-19 02:05:05.614] [INFO] Worker finished with code 0 and signal null
[2019-12-19 02:05:06.289] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js:26:5)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js:25:3)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
[2019-12-19 02:05:06.290] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js:25:3)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
    at Object.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2019-12-19 02:05:06.291] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Object.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/mocha.js:334:36
[2019-12-19 02:05:06.291] [INFO] Worker: Patching describe
[2019-12-19 02:05:06.291] [INFO] Worker: Patching describe.skip
[2019-12-19 02:05:06.291] [INFO] Worker: Patching describe.only
[2019-12-19 02:05:06.291] [INFO] Worker: Patching it
[2019-12-19 02:05:06.291] [INFO] Worker: Patching it.only
[2019-12-19 02:05:06.291] [INFO] Worker: Patching it.skip
[2019-12-19 02:05:06.291] [INFO] Worker: Copying it.retries
[2019-12-19 02:05:06.291] [INFO] Worker: Patching context
[2019-12-19 02:05:06.291] [INFO] Worker: Patching context.skip
[2019-12-19 02:05:06.291] [INFO] Worker: Patching context.only
[2019-12-19 02:05:06.291] [INFO] Worker: Patching specify
[2019-12-19 02:05:06.291] [INFO] Worker: Patching specify.only
[2019-12-19 02:05:06.291] [INFO] Worker: Patching specify.skip
[2019-12-19 02:05:06.291] [INFO] Worker: Copying specify.retries
[2019-12-19 02:05:06.292] [INFO] Worker: Patching describe
[2019-12-19 02:05:06.292] [INFO] Worker: Patching describe.skip
[2019-12-19 02:05:06.292] [INFO] Worker: Patching describe.only
[2019-12-19 02:05:06.292] [INFO] Worker: Patching it
[2019-12-19 02:05:06.292] [INFO] Worker: Patching it.only
[2019-12-19 02:05:06.292] [INFO] Worker: Patching it.skip
[2019-12-19 02:05:06.292] [INFO] Worker: Copying it.retries
[2019-12-19 02:05:06.292] [INFO] Worker: Patching context
[2019-12-19 02:05:06.292] [INFO] Worker: Patching context.skip
[2019-12-19 02:05:06.292] [INFO] Worker: Patching context.only
[2019-12-19 02:05:06.292] [INFO] Worker: Patching specify
[2019-12-19 02:05:06.292] [INFO] Worker: Patching specify.only
[2019-12-19 02:05:06.292] [INFO] Worker: Patching specify.skip
[2019-12-19 02:05:06.292] [INFO] Worker: Copying specify.retries
[2019-12-19 02:05:06.294] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js:30:5)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js:29:3)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
[2019-12-19 02:05:06.295] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Suite.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js:29:3)
    at Object.create (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/common.js:140:19)
    at context.describe.context.context (/Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:781:37
    at Object.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2019-12-19 02:05:06.295] [INFO] Worker: Looking for /Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js in Error
    at findCallLocation (/Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:792:17)
    at /Users/dididi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.0/out/worker/bundle.js:783:30
    at Object.<anonymous> (/Users/dididi/workspaces/effy/effy-functions/functions/test/db.user.online.test.js:14:1)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha/lib/mocha.js:334:36
[2019-12-19 02:05:06.299] [INFO] 

[2019-12-19 02:05:06.305] [INFO] 
  0 passing (8ms)

[2019-12-19 02:05:06.306] [INFO] 

[2019-12-19 02:05:06.307] [INFO] Worker: Converting tests and suites
[2019-12-19 02:05:06.308] [INFO] Received tests from worker
[2019-12-19 02:05:06.348] [INFO] Worker finished with code 0 and signal null
[2019-12-19 02:06:22.490] [INFO] Running test(s) ["/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js: auth"] of /Users/dididi/workspaces/effy/effy-functions/functions
[2019-12-19 02:06:22.646] [INFO] Worker: Using the mocha package at /Users/dididi/workspaces/effy/effy-functions/functions/node_modules/mocha
[2019-12-19 02:06:22.736] [INFO] Worker: Loading files
[2019-12-19 02:06:22.737] [INFO] Worker: Running tests
[2019-12-19 02:06:22.980] [INFO] Received {"type":"suite","suite":"undefined: ","state":"running"}
[2019-12-19 02:06:22.982] [INFO] Received {"type":"suite","suite":"/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js: auth","state":"running"}
[2019-12-19 02:06:23.143] [INFO] Received {"type":"test","test":"/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js: auth \"before all\" hook in \"auth\"","state":"failed","message":"Error: Failed to read credentials from file functions/effy-app-dev-firebase-adminsdk-93f13-ec8fa1d5d9.json: Error: ENOENT: no such file or directory, open 'functions/effy-app-dev-firebase-adminsdk-93f13-ec8fa1d5d9.json'\n    at FirebaseAppError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:42:28)\n    at FirebaseAppError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:88:28)\n    at new FirebaseAppError (node_modules/firebase-admin/lib/utils/error.js:123:28)\n    at readCredentialFile (node_modules/firebase-admin/lib/auth/credential.js:353:15)\n    at credentialFromFile (node_modules/firebase-admin/lib/auth/credential.js:332:27)\n    at new ApplicationDefaultCredential (node_modules/firebase-admin/lib/auth/credential.js:307:32)\n    at FirebaseNamespaceInternals.initializeApp (node_modules/firebase-admin/lib/firebase-namespace.js:61:34)\n    at FirebaseNamespace.initializeApp (node_modules/firebase-admin/lib/firebase-namespace.js:408:30)\n    at Object.<anonymous> (endpoints/ignore.admin.js:3:4)\n    at Module._compile (internal/modules/cjs/loader.js:786:30)","decorations":[]}
[2019-12-19 02:06:23.163] [INFO] Received {"type":"suite","suite":"/Users/dididi/workspaces/effy/effy-functions/functions/test/auth.online.test.js: auth","state":"completed","description":"181ms"}
[2019-12-19 02:06:23.163] [INFO] Received {"type":"suite","suite":"undefined: ","state":"completed","description":"183ms"}
[2019-12-19 02:06:23.164] [INFO] Received {"type":"finished"}
[2019-12-19 02:06:23.172] [INFO] Worker finished

```

**Comment by dfdgsdfg** [comment]
Now, works just fine.

I make mistake on spec file.

Thanks for great works. 👍 👍 💯
