### ISSUE TITLE
Error: Cannot find module 'ts-node/register'

### ISSUE THREAD

**Issue by Almenon** [hbenl/vscode-mocha-test-adapter#88]
I installed ts-node globally but mocha can't find it. 

```
	"settings": {
		"mochaExplorer.files": "test/**/*.ts",
		"mochaExplorer.require": "ts-node/register"
	}
```

version 2.2.2 of the extension

```
C:\dev\AREPL-vscode>node -v
v12.14.1

C:\dev\AREPL-vscode>npm -v
6.13.4

C:\dev\AREPL-vscode>npm list --depth=1 -g
C:\Users\almenon\AppData\Roaming\npm
+-- ts-node@8.6.2
| +-- arg@4.1.3
| +-- diff@4.0.2
| +-- make-error@1.3.5
| +-- source-map-support@0.5.16
| `-- yn@3.1.1
`-- typescript@3.7.5
```

```
Error: Cannot find module 'ts-node/register'
Require stack:
- c:\Users\almenon\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.2.2\out\worker\bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at execute (c:\Users\almenon\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.2.2\out\worker\bundle.js:1710:13)
    at c:\Users\almenon\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.2.2\out\worker\bundle.js:1671:9
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\almenon\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.2.2\out\worker\bundle.js:81:58)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\almenon\\.vscode\\extensions\\hbenl.vscode-mocha-test-adapter-2.2.2\\out\\worker\\bundle.js'
  ]
}
```

Workaround: install ts-node locally

**Comment by hbenl** [comment]
This is the same behavior that mocha shows when used without this extension.
Since the extension is supposed to follow the behavior of mocha as closely as possible, I won't change this.
