### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-mocha-test-adapter#9]
From Output/Log (Window)
```
[2018-08-22 21:49:28.448] [renderer3] [error] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at codeCoverage.updateDecorationByFile (C:\Users\____\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.17\lib\coverage\code-coverage.js:53:57)
	at vscode.window.onDidChangeActiveTextEditor.editor (C:\Users\_____\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.17\changesNotification.js:20:30)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:773:112
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:771:330)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:983)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:701)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:767)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:670:536)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:669:452
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:672:575
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:903
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:218)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:713)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
Needless to say that nothing works.

**Comment by Spown** [comment]
oh, sorry that is from the ``mocha-sidebar`` extension, that I removed just before I've installed this one
