### ISSUE TITLE
require cannot find module in yarn workspaces monorepo

### ISSUE THREAD

**Issue by rtbo** [hbenl/vscode-mocha-test-adapter#97]
When opening a yarn workspaces monorepo in a multi-root workspace (a monorepo - each package in a workspace folder), the extension reports an error:
```
[2020-03-30 18:07:42.632] [INFO] Test Explorer found
[2020-03-30 18:07:42.632] [INFO] Creating adapter for /home/remi/dev/test/monorepo
[2020-03-30 18:07:42.632] [INFO] Registering adapter for /home/remi/dev/test/monorepo
[2020-03-30 18:07:42.633] [INFO] Loading test files of /home/remi/dev/test/monorepo
[2020-03-30 18:07:42.637] [INFO] Creating adapter for /home/remi/dev/test/monorepo/packages/lib1
[2020-03-30 18:07:42.638] [INFO] Registering adapter for /home/remi/dev/test/monorepo/packages/lib1
[2020-03-30 18:07:42.638] [INFO] Loading test files of /home/remi/dev/test/monorepo/packages/lib1
[2020-03-30 18:07:42.638] [INFO] Creating adapter for /home/remi/dev/test/monorepo/packages/lib2
[2020-03-30 18:07:42.638] [INFO] Registering adapter for /home/remi/dev/test/monorepo/packages/lib2
[2020-03-30 18:07:42.639] [INFO] Loading test files of /home/remi/dev/test/monorepo/packages/lib2
[2020-03-30 18:07:42.639] [INFO] Initialization finished
[2020-03-30 18:07:42.640] [DEBUG] Using working directory: /home/remi/dev/test/monorepo/packages/lib1
[2020-03-30 18:07:42.652] [DEBUG] Using working directory: /home/remi/dev/test/monorepo/packages/lib2
[2020-03-30 18:07:42.709] [INFO] Adapter disabled for this folder, loading cancelled
[2020-03-30 18:07:42.864] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":["ts-node/register"],"exit":false}
[2020-03-30 18:07:42.865] [DEBUG] Looking for test files ["test/**/*.ts"] in /home/remi/dev/test/monorepo/packages/lib1
[2020-03-30 18:07:42.882] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":["ts-node/register"],"exit":false}
[2020-03-30 18:07:42.883] [DEBUG] Looking for test files ["test/**/*.ts"] in /home/remi/dev/test/monorepo/packages/lib2
[2020-03-30 18:07:42.895] [DEBUG] Found test files ["/home/remi/dev/test/monorepo/packages/lib1/test/index.ts"]
[2020-03-30 18:07:42.915] [DEBUG] Using nodePath: /home/remi/.nvm/versions/node/v13.9.0/bin/node
[2020-03-30 18:07:42.917] [DEBUG] Using environment variables from config: {}
[2020-03-30 18:07:42.929] [DEBUG] Found test files ["/home/remi/dev/test/monorepo/packages/lib2/test/index.ts"]
[2020-03-30 18:07:42.943] [DEBUG] Using nodePath: /home/remi/.nvm/versions/node/v13.9.0/bin/node
[2020-03-30 18:07:42.943] [DEBUG] Using environment variables from config: {}
[2020-03-30 18:07:42.974] [INFO] Worker: Using the mocha package at /home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/node_modules/mocha
[2020-03-30 18:07:42.998] [INFO] Worker: Using the mocha package at /home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/node_modules/mocha
[2020-03-30 18:07:43.031] [INFO] Worker: Patching Mocha
[2020-03-30 18:07:43.031] [INFO] Worker: Trying require('ts-node/register')
[2020-03-30 18:07:43.033] [INFO] Worker: Caught error Error: Cannot find module 'ts-node/register'
Require stack:
- /home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at execute (/home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:1710:13)
    at /home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:1671:9
    at Generator.next (<anonymous>)
    at fulfilled (/home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js:81:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/remi/.vscode/extensions/hbenl.vscode-mocha-test-adapter-2.2.2/out/worker/bundle.js'
  ]
}
```
However when I run the extension in development mode from the extension host, I don't have this error!
What can cause this?

I have made a simple package to reproduce this:
```
git clone https://github.com/rtbo/mocha-ts-monorepo
cd mocha-ts-monorepo
yarn install
code workspace.code-workspace
```
When running mocha directly from the packages dirs, everything run fine.

**Comment by rtbo** [comment]
when running the extension in development, `ts-node/register` is resolved here:
`vscode-mocha-test-adapter/node_modules/ts-node/register/index.js`, hence the difference of behavior

**Comment by rtbo** [comment]
the problem is actually that yarn place dev dependencies not in `package/node_modules`, but in `project_root/node_modules` which is not search in this configuration.

**Comment by hbenl** [comment]
That took me some time to figure out (thanks for the sample project, that helped a lot!).
Here's why this works on the command line but not with this extension:
When searching for a file to `require()`, node goes through all the parents of the directory containing the file which contains the `require()` call. When you call mocha on the command line, `ts-node/register` will be required by one of the scripts in the mocha package, so node will find ts-node because it is installed in the same directory as mocha (assuming you are using the mocha package from `project_root/node_modules`). By the way, if you use a globally installed mocha package (and don't have ts-node installed globally), you will get the same error as with the extension!
If you use this extension, `ts-node/register` will be required by one of the scripts in the extension, so ts-node would only be found if it was part of the extension (which is the case when you're debugging the extension but not when you're using the production version of it).

So the solution was to add the directory containing the mocha package and all its parent directories to node's search path (similar to the patch you wrote, but that added the parents of the current working directory, which happened to work in your case but is not what mocha usually does).
I have added this to version 2.3.0 of this extension. You will also have to add
```
"mochaExplorer.mochaPath": "../../node_modules/mocha"
```
to `packages/lib1/.vscode/settings.json` and `packages/lib2/.vscode/settings.json` to ensure that the extension uses the mocha package installed in `project_root/node_modules`.

**Comment by rtbo** [comment]
looks great, thank you.
