### ISSUE TITLE
Tests not detected for esm written tests

### ISSUE THREAD

**Issue by robertdumitrescu** [hbenl/vscode-mocha-test-adapter#99]
Hey,

I have tests that are importing esm modules in Node.js and when I try to detect the tests in Test Explorer UI via Mocha Explorer, it gives me the following error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: c:\Users\rober\gitRepos\royal-fiber\src\css.Helper.Spec.js
require() of ES modules is not supported.
require() of c:\Users\rober\gitRepos\royal-fiber\src\css.Helper.Spec.js from c:\Users\rober\gitRepos\royal-fiber\node_modules\mocha\lib\mocha.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename css.Helper.Spec.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from c:\Users\rober\gitRepos\royal-fiber\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at c:\Users\rober\gitRepos\royal-fiber\node_modules\mocha\lib\mocha.js:314:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (c:\Users\rober\gitRepos\royal-fiber\node_modules\mocha\lib\mocha.js:311:14)
    at Mocha.run (c:\Users\rober\gitRepos\royal-fiber\node_modules\mocha\lib\mocha.js:900:10)
    at execute (c:\Users\rober\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.2.2\out\worker\bundle.js:1723:19) {
  code: 'ERR_REQUIRE_ESM'
}
```

using this configuration:

```
    "mochaExplorer.files": "**/*.Spec.js",
    "mochaExplorer.monkeyPatch": false,
    "mochaExplorer.logpanel": true,
```

And tests being like that:

```
'use strict';

import chai from 'chai';
import CssHelper from './css.Helper.js';
// const chai = require('chai');
// const CssHelper = require('./css.Helper');
let expect = chai.expect;

describe('CssHelper', () => {

    describe('-> percentify', () => {
        it('should return the given value with appended percent symbol', async () => {
            let initial = 1;

            let expected = '1%';
            let actual = CssHelper.percentify(initial);
            expect(actual).to.deep.equal(expected);
        });
    });
});
```

Then when I modify settings.json like so to avoid calling directly mocha.js: 

```
    "mochaExplorer.files": "**/*.Spec.js",
    "mochaExplorer.mochaPath": "node_modules/mocha/bin/_mocha",
    "mochaExplorer.monkeyPatch": false,
    "mochaExplorer.logpanel": true,
```

It doesn't detect any tests and the Output from Mocha Explorer Log is like this:

```
[2020-04-02 08:05:21.780] [INFO] c:\Users\rober\gitRepos\royal-fiber\.vscode\settings.json was saved - checking if this affects c:\Users\rober\gitRepos\royal-fiber
[2020-04-02 08:05:21.780] [INFO] Sending autorun event
[2020-04-02 08:05:21.974] [INFO] Configuration changed
[2020-04-02 08:05:21.976] [INFO] Reloading because mochaExplorer.mochaPath changed
[2020-04-02 08:05:21.976] [INFO] Loading test files of c:\Users\rober\gitRepos\royal-fiber
[2020-04-02 08:05:21.979] [DEBUG] Using working directory: c:\Users\rober\gitRepos\royal-fiber
[2020-04-02 08:05:22.254] [DEBUG] Using Mocha options: {"ui":"bdd","timeout":2000,"retries":0,"requires":[],"exit":false}
[2020-04-02 08:05:22.254] [DEBUG] Looking for test files ["**/*.Spec.js"] in c:\Users\rober\gitRepos\royal-fiber
[2020-04-02 08:05:22.294] [DEBUG] Found test files ["c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\css.Helper.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\DOM.Helper.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\DOM.Service.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\node.Service.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\ranking.Helper.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\royalFiber.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\src\\validation.Helper.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\tests\\e2e\\helpers\\sanitiziation.Helper.Spec.js","c:\\Users\\rober\\gitRepos\\royal-fiber\\tests\\e2e\\tests\\initialBuild.Spec.js"]
[2020-04-02 08:05:22.377] [DEBUG] Using nodePath: C:\Program Files\nodejs\node.exe
[2020-04-02 08:05:22.378] [DEBUG] Using environment variables from config: {}
[2020-04-02 08:05:22.448] [INFO] Worker: Using the mocha package at c:\Users\rober\gitRepos\royal-fiber\node_modules\mocha\bin\_mocha
[2020-04-02 08:05:22.637] [ERROR] [31mError: No test files found: "test"[39m

[2020-04-02 08:05:22.643] [INFO] Worker finished with code 1 and signal null
```

Please help. Probably I am dumb somewhere. :D

**Comment by hbenl** [comment]
No, you're not dumb ;)
Support for ESM is a new feature in Mocha 7.1 and I had to make a small change to this extension to also support it. It should work in version 2.3.0.
